### ISSUE TITLE
cryolo picking crashes when no particles were picked from a certain micrograph.

### ISSUE THREAD

**Issue by genisvalentin** [scipion-em/scipion-em-sphire#68]
Hi! The protocol for cryolo-picking crashes when no particles were picked by cryolo in a certain micrograph. The plugin tries to read the picked particles, but crashes because there are no picks and is trying to read an empty file. Below is the error traceback. 

Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/genis/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 201, in run
    self._run()
  File "/home/genis/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 1419, in _run
    self._runSteps(startIndex)
  File "/home/genis/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 1270, in _runSteps
    self._stepsExecutor.runSteps(self._steps,
  File "/home/genis/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/executor.py", line 131, in runSteps
    stepsCheckCallback()
  File "/home/genis/anaconda3/envs/scipion3/lib/python3.8/site-packages/pwem/protocols/protocol_particles_picking.py", line 308, in _stepsCheck
    self._checkNewOutput()
  File "/home/genis/anaconda3/envs/scipion3/lib/python3.8/site-packages/pwem/protocols/protocol_particles_picking.py", line 407, in _checkNewOutput
    newDoneUpdated = self._updateOutputCoordSet(newDone, streamMode)
  File "/home/genis/anaconda3/envs/scipion3/lib/python3.8/site-packages/pwem/protocols/protocol_particles_picking.py", line 469, in _updateOutputCoordSet
    self.readCoordsFromMics(outputDir, micDoneList, outputCoords)
  File "/home/genis/anaconda3/envs/scipion3/lib/python3.8/site-packages/sphire/protocols/protocol_cryolo_picking.py", line 260, in readCoordsFromMics
    for x, y, score in reader.iterCoords():
  File "/home/genis/anaconda3/envs/scipion3/lib/python3.8/site-packages/sphire/convert.py", line 134, in iterCoords
    table = emtable.Table(fileName=self._file.name)
  File "/home/genis/anaconda3/envs/scipion3/lib/python3.8/site-packages/emtable/metadata.py", line 329, in __init__
    self.read(fileName, tableName)
  File "/home/genis/anaconda3/envs/scipion3/lib/python3.8/site-packages/emtable/metadata.py", line 367, in read
    self.readStar(f, tableName)
  File "/home/genis/anaconda3/envs/scipion3/lib/python3.8/site-packages/emtable/metadata.py", line 359, in readStar
    reader = _Reader(inputFile,
  File "/home/genis/anaconda3/envs/scipion3/lib/python3.8/site-packages/emtable/metadata.py", line 162, in __init__
    self._findDataLine(self._file, dataStr)
  File "/home/genis/anaconda3/envs/scipion3/lib/python3.8/site-packages/emtable/metadata.py", line 222, in _findDataLine
    raise Exception("'%s' block was not found" % dataStr)
Exception: 'data_' block was not found

**Comment by delarosatrevin** [comment]
I think that issue has been solved already. Can you check if you have the
latest version of the plugin?

**Comment by genisvalentin** [comment]
Indeed, the problem is fixed. I already had the latest version of the plugin, but I needed to update the cryolo environment manually to solve the issue.
