### ISSUE TITLE
Issue with empty cbox files

### ISSUE THREAD

**Issue by JoQCcoz** [scipion-em/scipion-em-sphire#83]
I'm getting a issue where scipion tries to read an empty cbox file and cannot locate the data_cryolo table with iterating through the file. I'm not sure why it even creates that empty file since cryolo doesn't create it.

```
Traceback (most recent call last):
  File "/ddn/gs1/tools/cryoem/scipion_env/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 201, in run
    self._run()
  File "/ddn/gs1/tools/cryoem/scipion_env/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 1461, in _run
    self._runSteps(startIndex)
  File "/ddn/gs1/tools/cryoem/scipion_env/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 1303, in _runSteps
    self._stepsExecutor.runSteps(self._steps,
  File "/ddn/gs1/tools/cryoem/scipion_env/lib/python3.8/site-packages/pyworkflow/protocol/executor.py", line 131, in runSteps
    stepsCheckCallback()
  File "/ddn/gs1/tools/cryoem/scipion_env/lib/python3.8/site-packages/pwem/protocols/protocol_particles_picking.py", line 308, in _stepsCheck
    self._checkNewOutput()
  File "/ddn/gs1/tools/cryoem/scipion_env/lib/python3.8/site-packages/pwem/protocols/protocol_particles_picking.py", line 407, in _checkNewOutput
    newDoneUpdated = self._updateOutputCoordSet(newDone, streamMode)
  File "/ddn/gs1/tools/cryoem/scipion_env/lib/python3.8/site-packages/pwem/protocols/protocol_particles_picking.py", line 469, in _updateOutputCoordSet
    self.readCoordsFromMics(outputDir, micDoneList, outputCoords)
  File "/ddn/gs1/tools/cryoem/scipion_software/scipion-em-sphire/sphire/protocols/protocol_cryolo_picking.py", line 144, in readCoordsFromMics
    for x, y, z, score in reader.iterCoords(coordsFile):
  File "/ddn/gs1/tools/cryoem/scipion_software/scipion-em-sphire/sphire/convert.py", line 88, in iterCoords
    for row in Table.iterRows(filename, tableName='cryolo'):
  File "/ddn/gs1/tools/cryoem/scipion_env/lib/python3.8/site-packages/emtable/metadata.py", line 541, in iterRows
    reader = _Reader(f, tableName, **kwargs)
  File "/ddn/gs1/tools/cryoem/scipion_env/lib/python3.8/site-packages/emtable/metadata.py", line 165, in __init__
    self._findDataLine(self._file, dataStr)
  File "/ddn/gs1/tools/cryoem/scipion_env/lib/python3.8/site-packages/emtable/metadata.py", line 231, in _findDataLine
    raise Exception("'%s' block was not found" % dataStr)
Exception: 'data_cryolo' block was not found
```

I could fix the issue by skipping if the file size is zero but i'm pretty sure there is a better way to fix this issue:

sphire.protocols.protocol_cryolo_picking line 143:
Original line:
`if os.path.exists(coordsFile):`
My fix:
`if os.path.exists(coordsFile) and os.path.getsize(coordsFile) > 0:`

**Comment by azazellochg** [comment]
Can I see the plugin version and the full cryolo command used for picking

**Comment by JoQCcoz** [comment]
Here's the info from the log. I pulled the main branch of this repository today.
```
rotocol starts
Hostname: gn030701.hpc.niehs.nih.gov
PID: 3641157
pyworkflow: 3.0.29
plugin: sphire
plugin v: 3.1.1
currentDir: /ddn/gs1/home/bouvettej2/ScipionUserData/projects/20230306_AR2_0113_1-2-4
workingDir: Runs/000945_SphireProtCRYOLOPicking
runMode: Restart
          MPI: 1
      threads: 1
 Starting at step: 1
 Running steps 
```
And here is one example cryolo picking command from that log file:
```
eval "$(/ddn/gs1/tools/cryoem/miniconda3/condabin/conda shell.bash hook)"&& conda activate /ddn/gs1/tools/cryoem/cryolo-cu11 && cryolo_predict.py  -c Runs/000945_SphireProtCRYOLOPicking/extra/config.json -w /ddn/gs1/tools/cryoem/scipion_software/em/cryolo_model-202005_N63_c17/gmodel_phosnet_202005_N63_c17.h5 -i Runs/000945_SphireProtCRYOLOPicking/tmp/micrographs_1-16/ -o Runs/000945_SphireProtCRYOLOPicking/tmp/micrographs_1-16/ -t 0.050 -nc 2 -g 6 --cleanup
```
I'm using the latest version of cryolo (1.9.3) since i couldn't make the other ones work on A100 gpus.

**Comment by azazellochg** [comment]
Hmm, are you using picking in streaming? I suspect the empty cbox might be created by cryolo and then populated with coordinates, so scipion tried to read it too early

**Comment by azazellochg** [comment]
I could not reproduce this. If you run exactly the same cryolo command outside scipion, does it create any empty cbox files?

**Comment by delarosatrevin** [comment]
I think we added that catch some time ago, but might be in a similar
situation.

**Comment by azazellochg** [comment]
Ok, I understand. Still, could you run 

`conda activate /ddn/gs1/tools/cryoem/cryolo-cu11 && cryolo_predict.py  -c Runs/000945_SphireProtCRYOLOPicking/extra/config.json -w /ddn/gs1/tools/cryoem/scipion_software/em/cryolo_model-202005_N63_c17/gmodel_phosnet_202005_N63_c17.h5 -i Runs/000945_SphireProtCRYOLOPicking/tmp/micrographs_1-16/ -o Runs/000945_SphireProtCRYOLOPicking/tmp/micrographs_1-16/ -t 0.050 -nc 2 -g 6 --cleanup`

 from the project folder outside scipion and check for empty cbox files? Cryolo should not generate empty files so I dont understand why this happens. If there are no empty files and you do have the error when running exact same command inside scipion, we have a streaming problem. Adding more checks per each cbox file will slow down output creation step, so it's better to find the cause
